### ISSUE TITLE
How to use ? method getDescription is not defined. 

### ISSUE THREAD

**Issue by Frulko** [BetterVoice/iOS-SIP.js#1]
Hi, I just see your project about porting onSipCordova to 64Bit architecture. 

I already have an app which work with on-sip-cordova plugin but this plugin work only with 32bit.

I've cloned the repo but when I try to use it and I have got a problem : 
 the method "getDescription" is not defined. 

Can you give me a short example to instanciate and use your modified onsip-cordova plugin. 

Thanks.

**Comment by lylepratt** [comment]
I've provided an example in the readme.
