### ISSUE TITLE
Missing SDP when I call from iOS 8.4

### ISSUE THREAD

**Issue by LTroya** [BetterVoice/iOS-SIP.js#3]
While developing a sip application for iOS 8.4 Im finding that I am not able to initiniate a call. My FS server constantly complains that it will not accept a call in without a SDP, it seems that iOS is sending an invite without a corresponding sdp.

Using the same setup I am able to recieve calls from other divices (androids phones for example) but can't place a call from ios.

**Comment by lylepratt** [comment]
Are you still having problems with this?

**Comment by lylepratt** [comment]
Hi @LTroya I believe this may have been solved by https://github.com/BetterVoice/iOS-SIP.js/commit/3e8db5845130a7c5c14405a762c89ca53005a676
