### ISSUE TITLE
iOS-SIP.js not sending SDP on Invites

### ISSUE THREAD

**Issue by LTroya** [BetterVoice/iOS-SIP.js#4]
While developing a sip application for iOS 8.4 Im finding that I am not able to initiniate a call. My FS server constantly complains that it will not accept a call in without a SDP, it seems that iOS is sending an invite without a corresponding sdp.

Using the same setup I am able to recieve calls from other divices (androids phones for example) but can't place a call from ios.

**Comment by lylepratt** [comment]
Hmmm. What version of Freeswitch are you running? We are using this in production with Freeswitch without problems. Any thoughts @thomasquintana ?

**Comment by LTroya** [comment]
Sorry for the late, my FS version is 1.6

FS is configured to bypass media completely and only handles SIP. When iOS originates call i dont see media flowing from device. When another devices calls to iOS everything just works

It also complaints about no sdp on call and ask (FS) to enable 3pcc. Any hints?

**Comment by lylepratt** [comment]
Are you still having problems with this?

**Comment by LTroya** [comment]
It's working now. I downloaded the last library and change the config with the new update.

**Comment by KishoreJugge** [comment]
I am following your steps to compile ios-webrtc.
we already completed the installation steps.
We have no clue where to configure the User Agent as Shown in Example Usage heading. 

Please suggest in which file I need to configure.

**Comment by lylepratt** [comment]
I'm not really sure I understand your question. You are supposed to use SIP.js with this. You'll configure the user agent in your javascript project.

**Comment by KishoreJugge** [comment]
Thanks for the reply. We do not have sip.js file in the project. Do we need to add the sip.js file? Great if you can send me the sample sip.js file. Do we need to configure the User Agent in the same sip.js file?

Thanks for your cooperation. I am very new newbie to the webrtc and js.

**Comment by lylepratt** [comment]
This project is a custom handler for SIP.js and it only works with SIP.js:
https://github.com/onsip/SIP.js
