### ISSUE TITLE
Can't deploy on iOS emulator

### ISSUE THREAD

**Issue by jricardovg** [BetterVoice/iOS-SIP.js#7]
Hi, i'm having some issues to deploy the app in the emulator. 

I'm following the instructions to configure the Xcode project, and i have downloaded the lib http://s3.bettervoice.com/webrtclibs/webrtc-ios-unified.a (x86+arm) and added to the Linked Frameworks and Libs

<img width="585" alt="screen shot 2015-11-10 at 5 32 00 pm" src="https://cloud.githubusercontent.com/assets/14277374/11078001/11ff26d8-87d1-11e5-81f4-ac6c417a9891.png">

This is the error that i'm getting:

<img width="545" alt="screen shot 2015-11-10 at 5 30 37 pm" src="https://cloud.githubusercontent.com/assets/14277374/11077954/cf567c28-87d0-11e5-98a6-413801ee8d44.png">

The Audio + VoIP Background Modes are enabled but the Xcode can't compile the source for the project.

the error is in the PluginMediaStream.swift file inside the Plugins

<img width="902" alt="screen shot 2015-11-10 at 5 34 38 pm" src="https://cloud.githubusercontent.com/assets/14277374/11078056/789f5278-87d1-11e5-83b0-61dab1492d4b.png">

regards.

**Comment by lylepratt** [comment]
Hi,

Unfortunately, x86 is not actually supported in that Unified WebRTC lib. Only armv7 + arm64. The x86 in the Readme was a mistake, and I have changed it to be "armv7 + arm64". 

For now, If you want to deploy in the simulator, you'll need to package your own WebRTC lib that contains proper support for x86 in the simulator.
